nome = input ('qual é o seu nome?')
idade = input ('quantos anos você tem?')
civil = input ('qual seu estado civil?')
filhos = input ('você tem filhos?')
país = input ('de qual país você é?')
estado = input ('de qual estado você é?')
cidade = input ('qual o mnome da sua cidade?')
bairro = input ('em qual bairro você mora?')
casa = input ('qual sua moradia, casa ou apartamento?')
reside = input ('quantas pessoas moram com você?')
casa1 = input ('sua moradia é própria(o), alugada(o), cedida(o)?')
carro = input ('você possui veículo?')
esporte = input ('pratica alguma atividade fisica?')
esporte1 = input ('qual tipo de atividade fisica você pratica?')
defi = input ('você possui alguma deficiencia?')
defii = input ('qual tipo de deficiencia?')


print('Nome: {}'.format(nome))
print('Idade: {}'.format(idade))
print('Estado Civil:{}'.format(civil))
print('Filhos: {}'.format(filhos))
print('País: {}'.format(país))
print('Estado: {} '.format(estado))
print('Cidade: {}'.format(cidade))
print('Bairro: {}'.format(bairro))
print('Moradia: {}'.format(casa))
print('Pessoas na mesma casa: {}'.format(reside))
print('Condições da Moradia: {}'.format(casa1))
print('Veículo: {}'.format(carro))
print('Pratica Atividade Física: {}'.format(esporte))
print('Tipo de Atividade Física: {}'.format(esporte1))
print('Deficiência:{}'.format(defi))
print('Tpo de Deficiência: {}'.format(defii))